language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - pyrus install -f pear/PHP_CodeSniffer-1.5.4
  - phpenv rehash
  - mysql -e 'create database joomla_ut;'

script:
  - phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .

branches:

notifications:
  webhooks:
    urls:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

